### ISSUE TITLE
Připomínky k šablonám

### ISSUE THREAD

**Issue by MilanPala** [MilanPala/Svatba#1]
- [x] Horní text "Tereza a Milan" lepší obrázek, aby to bylo pěkné i na retině
 - [x] Přidat další aktivní bod na spodní budovu
 - [x] Pozadí na full hd

**Comment by radeksir** [comment]
retina obrazky když dodá klára možno vyměni

**Comment by MilanPala** [comment]
@radeksir Mohl bys mi prosím posunout to kolo na rsvp od okrajů, tak 10 px maximálně. Nedaří se mi to, vždy se mi to rozpadne.

**Comment by MilanPala** [comment]
@radeksir Nahrál jsem retina logo, mohl bys ho poladit, aby mělo správný rozměr?

**Comment by MilanPala** [comment]
@radeksir Bylo by možné spodní dva checkboxy udělat, aby fungovaly jako radiobuttony? Tím, jak jsou přestylované se mi to nedaří upravit. Zkoušel jsem toto: http://stackoverflow.com/questions/4697941/jquery-make-checkboxes-act-like-radio-buttons

**Comment by radeksir** [comment]
vy jste se v tom zase vrtal co pane doktore ...

**Comment by radeksir** [comment]
upraveno

**Comment by MilanPala** [comment]
Díky za spolupráci
